subject = ['-', 'english', 'math', 'science', 'social studies', 'algebra',
           'assumed team teaching', 'chemistry', 'earth science', 'economics',
           'english 10', 'english 11', 'english 12', 'english 9', 'geometry',
           'global history 10', 'global history 9', 'living environment',
           'matched sections', 'math a', 'math b', 'other', 'physics', 'us government',
           'us government & economics', 'us history']
street_name = ['avenue', 'place', 'street', 'st', 'court']
park_playground = ['park', 'playground']
school_level = ['elementary', 'high school', 'high school transfer', 'k-2',
                'k-3', 'k-8', 'middle', 'yabc', 'elementary school', 'k-8 school',
                'middle school', 'transfer school', 'transfer high school', 'd75']
neighborhood_name = ['arrochar-shore acres', 'dongan hills', 'grant city', 'grymes hill',
                     'new springville', 'rosebank', 'silver lake', 'sunnyside', 'tompkinsville',
                     'bedford park/norwood', 'belmont', 'bronxdale', 'city island', 'east tremont',
                     'highbridge/morris heights', 'kingsbridge/jerome park', 'morris park/van nest',
                     'morrisania/longwood', 'mott haven/port morris', 'parkchester',
                     'pelham parkway south', 'riverdale', 'schuylerville/pelham bay', 'soundview',
                     'throgs neck', 'williamsbridge', 'airport la guardia', 'astoria', 'bayside',
                     'briarwood', 'college point', 'corona', 'elmhurst', 'far rockaway',
                     'flushing meadow park', 'flushing-north', 'flushing-south', 'forest hills',
                     'glendale', 'hammels', 'howard beach', 'jackson heights', 'jamaica estates',
                     'kew gardens', 'little neck', 'long island city', 'maspeth', 'middle village',
                     'oakland gardens', 'ozone park', 'rego park', 'ridgewood', 'rockaway park',
                     'south ozone park', 'whitestone', 'woodhaven', 'woodside', 'bath beach',
                     'bay ridge', 'bedford stuyvesant', 'bensonhurst', 'boerum hill', 'borough park',
                     'brighton beach', 'brooklyn heights', 'bushwick', 'canarsie', 'carroll gardens',
                     'clinton hill', 'cobble hill', 'cobble hill-west', 'crown heights',
                     'downtown-fulton ferry', 'downtown-fulton mall', 'downtown-metrotech',
                     'dyker heights', 'east new york', 'flatbush-central', 'flatbush-east',
                     'flatbush-lefferts garden', 'flatbush-north', 'fort greene', 'gowanus',
                     'gravesend', 'greenpoint', 'kensington', 'madison', 'midwood', 'mill basin',
                     'ocean hill', 'ocean parkway-north', 'park slope', 'park slope south',
                     'prospect heights', 'sheepshead bay', 'sunset park', 'williamsburg-central',
                     'williamsburg-east', 'williamsburg-north', 'williamsburg-south',
                     'windsor terrace', 'wyckoff heights', 'hillcrest', 'jamaica']

interest = ['animal science', 'architecture', 'business', 'communications',
            'computer science & technology', 'cosmetology', 'culinary arts',
            'engineering', 'environmental science', 'film/video', 'health professions',
            'hospitality, travel and tourism', 'humanities & interdisciplinary',
            'jrotc', 'law & government', 'performing arts',
            'performing arts/visual art & design', 'science & math', 'teaching',
            'visual art & design', 'zoned']

borough = ['brooklyn', 'manhattan', 'bronx',
           'staten island', 'queens', 'k', 'r', 'm', 'x', 'q']
agency = ['311', 'acs', 'bic', 'boe', 'bpl', 'cchr', 'ccrb', 'cuny', 'dca',
          'dcas', 'dcla', 'dcp', 'ddc', 'dep', 'dfta', 'dhs', 'dob', 'doc',
          'doe', 'dof', 'dohmh', 'doi', 'doitt', 'dop', 'doris', 'dot', 'dpr',
          'dsny', 'dvs', 'dycd', 'fdny', 'hpd', 'hra', 'law', 'lpc', 'nycem',
          'nycha', 'nychh', 'nypd', 'nypl', 'oath', 'qpl', 'sbs', 'sca', 'tlc',
          'edc', 'nypl-research', 'ocme']
agency_name = ['admin. for children services', 'board of correction', 'board of elections',
               'brooklyn public library', 'business integrity commission', 'campaign finance board',
               'city clerk', 'city council', 'city university', 'citywide pension contributions',
               'citywide savings initiatives', 'civil service commission', 'civilian complaint review bd.',
               'commission on human rights', 'community boards (all)', 'conflicts of interest board', 'd.o.i.t.t.',
               'debt service', 'department for the aging', 'department of buildings', 'department of city planning',
               'department of consumer affairs', 'department of correction', 'department of cultural affairs',
               'department of education', 'department of finance', 'department of investigation',
               'department of probation', 'department of sanitation', 'department of social services',
               'department of transportation', 'dept health & mental hygiene', 'dept of citywide admin srvces',
               'dept of environmental prot.', 'dept of parks and recreation', 'dept of records & info serv.',
               'dept. of design & construction', 'dept. of emergency management', 'dept. of homeless services',
               "dept. of veterans' services", 'dept. small business services', 'district attorney - bronx',
               'district attorney - kings', 'district attorney - n.y.', 'district attorney - queens',
               'district attorney - richmond', 'energy adjustment', 'equal employment practices com',
               'financial info. serv. agency', 'fire department', 'general reserve', 'health and hospitals corp.',
               'housing preservation & dev.', 'independent budget office', 'landmarks preservation comm.',
               'law department', 'lease adjustment', 'mayoralty', 'miscellaneous', 'new york public library',
               'ny public library - research', 'off. of prosec. & spec. narc.', 'office admin trials & hearings',
               'office of admin. tax appeals', 'office of collective barg.', 'office of payroll admin.',
               'office of the actuary', 'office of the comptroller', 'otps inflation adjustment', 'police department',
               'president,borough of brooklyn', 'president,borough of manhattan', 'president,borough of queens',
               'president,borough of s.i.', 'president,borough of the bronx', 'public administrator - bronx',
               'public administrator - n.y.', 'public administrator - queens', 'public administrator -richmond',
               'public administrator- brooklyn', 'public advocate', 'queens borough public library',
               'taxi & limousine commission', 'youth & community development']

vehicel_type = ['2 dr sedan', 'ambulance', 'bicycle', 'bike', 'box truck', 'bu', 'bus', 'carry all', 'convertible',
                'dp', 'ds', 'fb', 'fire truck', 'garbage or refuse', 'gg', 'large com veh(6 or more tires)',
                'livery vehicle', 'll', 'motorcycle', 'ms', 'other', 'passenger vehicle', 'pedicab', 'pick-up truck',
                'scooter', 'sedan', 'small com veh(4 tires)', 'sport utility / station wagon',
                'station wagon/sport utility vehicle', 'taxi', 'tk', 'tow truck / wrecker', 'tract', 'tractor truck diesel',
                'trail', 'trl', 'unknown', 'van', 'wagon']



